created bio
lab-brussels-1/group2hw pull request #30
Opened 2022-03-16 19:49 UTC by SWAPNACHEMBOTH

## Checklists

### General Checks

- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] All CI checks pass
- [ ] all conflicts are resolved (if any)
- [ ] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [ ] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

## Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work

2022-03-16 20:01 UTC, Alexander-Segovia commented
Hi @SWAPNACHEMBOTH There is a lot of HTML in your MD file, try using exclusively Markdown for this task and upload the changes :)

2022-03-17 23:45 UTC, prgrmfl requested changes
Hi @SWAPNACHEMBOTH 
1. You can do `npm install` and then do linting checks from your terminal/CLI.
2. - You should do `git checkout swapna` from your terminal, to go to your branch
    - Then use `git pull` command to update the master branch  
    - And use `git pull origin master` to update your branch-swapna with the latest changes in master branch  
    - make changes if any in your swapnabio.md file
    - `git add /people/swapnabio.md` to add your file and add other files if there are any changes you can also use `git add .` to add all the changed files
    - `git commit -m "commit message"` to commit the changes you added
    - `git push` to push the committed files to your branch in github

2022-03-17 23:45 UTC, prgrmfl commented on people/swapnabio.md
> +<h1 align="center">Hi 👋, I'm Swapna Chemboth. Currently living in Brussels,Belgium</h1>
Hi @SWAPNACHEMBOTH 
You can replace all the h1, h2.. with markdown equivalents such as '# heading' for h1

2022-03-17 23:45 UTC, prgrmfl commented on people/swapna.md
> +# Hi, this is Swapna
Maybe you can consider deleting this file, as there are two bio files with your name.

2022-03-19 13:24 UTC, merged